<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

<head>
    <title>Indicia demonstrations</title>
    <link rel="stylesheet" type="text/css" href="demo.css" />
    <link rel="stylesheet" type="text/css" href="../../media/css/default_site.css" />
    <link rel="stylesheet" type="text/css" href="../../media/themes/default/jquery-ui.custom.css" />
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
</head>
<body>
<div id="wrap"">
<h1>Indicia demonstrations</h1>
<?php
  require '../../client_helpers/data_entry_helper.php';
  echo data_entry_helper::system_check(true);

?>
<br/>
<p>The following list of demonstration pages illustrate service based Indicia functionality.</p>
<ol class="demolist">
<li>
<h2>Data Entry Demonstrations</h2>
<ol>
<li class="ui-widget-content ui-corner-all"><div  class="ui-widget-header"><a href="data_entry/basic_data_entry_tutorial.php" class="ui-widget-header">Basic Data Entry Tutorial</a></div>
<p>The data entry form which accompanies the <a href="http://code.google.com/p/indicia/wiki/TutorialBuildingBasicPage">Building a Basic Data Entry Page</a> tutorial.
View the source code in <a href="viewsource.php?file=data_entry/basic_data_entry_tutorial.php">basic_data_entry_tutorial.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="data_entry/test_data_entry.php">Data entry 2</a></div>
<p>A demonstration of a data entry page, allowing entry of a single occurrence at a time. Also includes some fields
for entering custom attributes. View the source code in <a href="viewsource.php?file=data_entry/test_data_entry.php">test_data_entry.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="data_entry/species_checklist.php">Checklist based data entry</a></div>
<p>A demonstration data entry page which includes a header for summary information and a grid allowing entry of multiple
occurrences. The grid contains a custom attribute for the entry of DAFOR abundance data per occurrence.
View the source code in <a href="viewsource.php?file=data_entry/species_checklist.php">species_checklist.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="data_entry/flickr.php">Linking to Flickr photos</a></div>
Simple data entry form, enhanced with a Flickr photo link tool allowing Flickr images to be tagged against occurrences. To use
this page you must have a Flickr account and you will be asked to authenticate when you first access the page.
View the source code in <a href="viewsource.php?file=data_entry/flickr.php">flickr.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="data_entry/file_upload.php">Uploading image files</a></div>
Same as the basic data entry tutorial form but with an additional file_box control for uploading image files.
View the source code in <a href="viewsource.php?file=data_entry/file_upload.php">file_upload.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="advanced_data_entry/header.php">Data entry wizard</a></div>
<p>A demonstration data entry "mini-site" which includes a wizard for entering a checklist of species found at a place and a distribution map
as a reward after a record has been contributed. The map also has a toolbar to allow switching to a mode for capturing polygon shaped occurrences
rather than just points or grid squares. View the source code in
<a href="viewsource.php?file=advanced_data_entry/header.php">header.php</a>,
<a href="viewsource.php?file=advanced_data_entry/list.php">list.php</a>,
<a href="viewsource.php?file=advanced_data_entry/save.php">save.php</a>,
<a href="viewsource.php?file=advanced_data_entry/success.php">success.php</a> and
<a href="viewsource.php?file=advanced_data_entry/map.php">map.php</a>.</p>
</li>
</ol>
</li>
<li>
<h2>Map Demonstrations</h2>
<ol>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="map_default.php">Default map</a></div>
<p>A demonstration of the default map generated by the data entry helper for selecting spatial reference. This is the simplest method, but also
 the least flexible.
View the source code in <a href="viewsource.php?file=map_default.php">map_default.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="map_modular.php">Modular map</a></div>
<p>Illustrates how a map and set of linked controls can be constructed to your requirements.
View the source code in <a href="viewsource.php?file=map_modular.php">map_modular.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="map_polygon_capture.php">Polygon capture data entry map</a></div>
<p>A data entry map set up for capture of polygons for occurrences.
View the source code in <a href="viewsource.php?file=map_polygon_capture.php">map_polygon_capture.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="map_tilecache.php">Tilecache layer</a></div>
<p>Advanced. Demonstrates how to load a tilecache layer as a map background layer for better performance. 
View the source code in <a href="viewsource.php?file=map_tilecache.php">map_tilecache.php</a>.</p>
</li>
</ol>
</li>
<li>
<h2>Report Demonstrations</h2>
<ol>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="reports/reports_and_charts.php">Reports and Charts</a></div>
<p>Demonstration of a simple report grid, as well as each of the chart options.
View the source code in <a href="viewsource.php?file=reports/reports_and_charts.php">reports_and_charts.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="reports/report_1.php">Report grid</a></div>
<p>Displays a report loaded into a grid.
View the source code in <a href="viewsource.php?file=reports/report_1.php">report_1.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="reports/accessing_report_data.php">Report service</a></div>
<p>Illustrates loading xml data from a report for download.
View the source code in <a href="viewsource.php?file=reports/accessing_report_data.php">accessing_report_data.php</a>.</p>
</li>
</ol>
</li>
<li>
<h2>Data Demonstrations</h2>
<ol>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="occurrence_grid.php">Occurrences grid</a></div>
<p>Browse a grid of occurrences captured by this instance of the Core Module. Also demonstrates viewing, commenting and editing existing occurrences.
View the source code in <a href="viewsource.php?file=occurrence_grid.php">occurrence_grid.php</a> and <a href="viewsource.php?file=occurrence.php">occurrence.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="valid.php">Validation service</a></div>
<p>Illustrates a JSON submission being sent to the validation services for a pre-check.
View the source code in <a href="viewsource.php?file=valid.php">valid.php</a>.</p>
</li>
</ol>
</li>
<!--
These 2 demos need to be fixed and refined.
<li><a href="test_treeview.php">Demonstration of 3 term based treeviews.</a></li>
<li><a href="../../index.php/services/data/location?mode=xml&view=detail">List the locations as XML by calling the Data service</a></li>
-->
<li>
<h2>Web-site User Control Demonstrations</h2>
<ol>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="login_control.php">Web-site Login Control</a></div>
<p>Designed to be used on client web-sites to allow site users to be authenticated by using their user credentials stored 
on indicia core. It returns their user id and site role to the client web-site. This can then be used to control what the 
user can do on the site and to associate any data submissions with the correct user id.
View the source code in <a href="viewsource.php?file=login_control.php">login_control.php</a>.</p>
</li>
<li class="ui-widget-content ui-corner-all"><div class="ui-widget-header"><a href="forgotten_password_control.php">Web-site Forgotten Password Control</a></div>
<p>Designed to be used on client web-sites to allow site users to reset the password for their user credentials stored 
on indicia core. It triggers an email to their registered email address which contains a link to a reset password page on indicia core.
View the source code in <a href="viewsource.php?file=forgotten_password_control.php">forgotten_password_control.php</a>.</p>
</li>
</ol>
</li>
</ol>
</div>
</body>
