CREATE TABLE scratchpad_lists
(
  id serial NOT NULL, -- Primary key and unique identifier.
  title character varying, -- Title provided for the scratchpad list. Set to the date & time if not provided.
  description character varying, -- Description of the scratchpad list.
  entity character varying NOT NULL, -- Database entity that this list contains items from.
  created_on timestamp without time zone NOT NULL, -- Date this record was created.
  created_by_id integer NOT NULL, -- Foreign key to the users table (creator).
  updated_on timestamp without time zone NOT NULL, -- Date this record was updated.
  updated_by_id integer NOT NULL, -- Foreign key to the users table (updater).
  website_id integer NOT NULL, -- Foreign key to the websites table.
  expires_on timestamp without time zone, -- Sets a date and time after which the scratchpad list is expired and made available for garbage collection.
  deleted boolean NOT NULL DEFAULT false, -- Has this record been deleted?
  CONSTRAINT pk_scratchpad_lists PRIMARY KEY (id),
  CONSTRAINT fk_scratchpad_lists_creator FOREIGN KEY (created_by_id)
      REFERENCES users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_scratchpad_lists_updater FOREIGN KEY (updated_by_id)
      REFERENCES users (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_scratchpad_lists_website FOREIGN KEY (website_id)
      REFERENCES websites (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);

COMMENT ON TABLE scratchpad_lists
  IS 'List of saved reporting scratchpad results sets. Allows users to create temporary lists of species or other entities that can then be fed into reports as an input parameter.';
COMMENT ON COLUMN scratchpad_lists.id IS 'Primary key and unique identifier.';
COMMENT ON COLUMN scratchpad_lists.title IS 'Title provided for the scratchpad list. Set to the date & time if not provided.';
COMMENT ON COLUMN scratchpad_lists.description IS 'Description of the scratchpad list.';
COMMENT ON COLUMN scratchpad_lists.entity IS 'Database entity that this list contains items from.';
COMMENT ON COLUMN scratchpad_lists.created_on IS 'Date this record was created.';
COMMENT ON COLUMN scratchpad_lists.created_by_id IS 'Foreign key to the users table (creator).';
COMMENT ON COLUMN scratchpad_lists.updated_on IS 'Date this record was updated.';
COMMENT ON COLUMN scratchpad_lists.updated_by_id IS 'Foreign key to the users table (updater).';
COMMENT ON COLUMN scratchpad_lists.website_id IS 'Foreign key to the websites table.';
COMMENT ON COLUMN scratchpad_lists.expires_on IS 'Sets a date and time after which the scratchpad list is expired and made available for garbage collection.';
COMMENT ON COLUMN scratchpad_lists.deleted IS 'Has this record been deleted?';

-- Index: fki_scratchpad_lists_creator

CREATE INDEX fki_scratchpad_lists_creator
  ON scratchpad_lists
  USING btree
  (created_by_id);

-- Index: fki_scratchpad_lists_website

CREATE INDEX fki_scratchpad_lists_website
  ON scratchpad_lists
  USING btree
  (website_id);

CREATE TABLE scratchpad_list_entries
(
  id serial NOT NULL, -- Primary key and unique identifier.
  scratchpad_list_id integer NOT NULL, -- Foreign key to the scratchpad_lists table. Identifies the list the entry belongs to.
  entry_id integer NOT NULL, -- ID of the record from the table identified by entity which is in the list.
  CONSTRAINT pk_scratchpad_list_entries PRIMARY KEY (id),
  CONSTRAINT fk_scratchpad_list_entries_scratchpad_lists FOREIGN KEY (scratchpad_list_id)
      REFERENCES scratchpad_lists (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);

COMMENT ON TABLE scratchpad_list_entries
  IS 'Individual entries on a list generated by the scratchpad tool. For example the ID of a species that has been chosen in a list that will be fed into reports.';
COMMENT ON COLUMN scratchpad_list_entries.id IS 'Primary key and unique identifier.';
COMMENT ON COLUMN scratchpad_list_entries.scratchpad_list_id IS 'Foreign key to the scratchpad_lists table. Identifies the list the entry belongs to.';
COMMENT ON COLUMN scratchpad_list_entries.entry_id IS 'ID of the record from the table identified by entity which is in the list.';

-- DROP INDEX fki_scratchpad_list_entries_scratchpad_lists;

CREATE INDEX fki_scratchpad_list_entries_scratchpad_lists
  ON scratchpad_list_entries
  USING btree
  (scratchpad_list_id);
