<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Indicia demonstrations</title>
    <link rel="stylesheet" type="text/css" href="demo.css" />
</head>
<body>
<div id="wrap"">
<h1>Indicia demonstrations</h1>
<?php
  // for first time usage, check that the data entry config file exists.
  if (!file_exists('data_entry/data_entry_config.php')) {
    rename('data_entry/data_entry_config.php.example', 'data_entry/data_entry_config.php');
  }

?>
<p>The following list of demonstration pages illustrate service based Indicia functionality.</p>
<ol class="demolist">
<li><a href="data_entry/test_data_entry.php">Basic Data Entry</a>
<p>A demonstration of a basic data entry page, allowing entry of a single occurrence at a time. Also includes some fields
for entering custom attributes. View the source code in <a href="viewsource.php?file=data_entry/test_data_entry.php">test_data_entry.php</a>.</p>
</li>
<li><a href="data_entry/species_checklist.php">Demonstration checklist based data entry page</a>
<p>A demonstration data entry page which includes a header for summary information and a grid allowing entry of multiple
occurrences. View the source code in <a href="viewsource.php?file=data_entry/species_checklist.php">species_checklist.php</a>.</p>
</li>
<li><a href="advanced_data_entry/header.php">A Data Entry Wizard</a>
<p>A demonstration data entry "mini-site" which includes a wizard for entering a checklist of species found at a place and a distribution map
as a reward after a record has been contributed. The map also has a toolbar to allow switching to a mode for capturing polygon shaped occurrences
rather than just points or grid squares. View the source code in <a href="viewsource.php?file=advanced_data_entry/header.php">species_checklist.php</a>.</p>
</li>
<li><a href="map_data_entry_helper.php">Data entry map</a>
<p>A demonstration of the default map generated by the data entry helper.
View the source code in <a href="viewsource.php?file=map_data_entry_helper.php">map_data_entry_helper.php</a>.</p>
</li>
<li><a href="map_javascript_classes.php">JavaScript Data entry map</a>
<p>A demonstration of the same map, but generated by direct access to the JavaScript mapping classes which offers more flexibility
and showing the support for OS Landranger maps.
View the source code in <a href="viewsource.php?file=map_javascript_classes.php">map_javascript_classes.php</a>.</p>
</li>
<li><a href="map_polygon_capture.php">Polygon capture data entry map</a>
<p>A data entry map set up for capture of polygons for occurrences.
View the source code in <a href="viewsource.php?file=map_polygon_capture.php">map_polygon_capture.php</a>.</p>
</li>
<li><a href="occurrence_grid.php">Occurrences grid</a>
<p>Browse a grid of occurrences captured by this instance of the Core Module. Also demonstrates viewing, commenting and editing existing occurrences.
View the source code in <a href="viewsource.php?file=occurrence_grid.php">occurrence_grid.php</a> and <a href="viewsource.php?file=occurrence.php">occurrence.php</a>.</p>
</li>
<li><a href="valid.php">Validation service</a>
<p>Illustrates a JSON submission being sent to the validation services for a pre-check.
View the source code in <a href="viewsource.php?file=valid.php">valid.php</a>.</p>
</li>

<!--
These 2 demos need to be fixed and refined.
<li><a href="test_treeview.php">Demonstration of 3 term based treeviews.</a></li>
<li><a href="../../index.php/services/data/location?mode=xml&view=detail">List the locations as XML by calling the Data service</a></li>
-->
</ol>
</div>
</body>
